SQUARE_WIDTH = 22
SQUARE_HEIGHT = 22
SCREEN_ROWS = 25
SCREEN_COLUMNS = 50
SCREEN_WIDTH = SQUARE_WIDTH * SCREEN_COLUMNS
SCREEN_HEIGHT = SQUARE_HEIGHT * SCREEN_ROWS
GREEN = (55, 125, 61)
BACKGROUND_COLOR = GREEN
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
LINE_COLOR = (96, 245, 66)
BACKGROUND_NIGHT_COLOR = BLACK
EMPTY_SQUARE = "EMPTY"
MINE_SQUARE ="MINE"
FLAG_SQUARE = "FLAG"

GRASS_WIDTH = 30
GRASS_HEIGHT = 40
MINE_WIDTH = 3 * SQUARE_WIDTH
MINE_HEIGHT = 1 * SQUARE_HEIGHT

FLAG_WIDTH = 4
FLAG_HEIGHT = 4
SOLDIER_WIDTH = 4
SOLDIER_HEIGHT = 4

FONT_NAME = "Calibri"
INITIAL_TEXT_1 = "Welcome to The Flag game."
INITIAL_TEXT_2 = "Have Fun!"

EXPLOSION = "explotion.png"
FLAG = "flag.png"
GRASS = "grass.png"
INJURY = "injury.png"
MINE = "mine.png"
SNAKE = "snake.png"
SOLDIER = "soldier.png"
SOLDIER2 = "soldier2.png"
SOLDIER_NIGHT = "soldier_night"

INITIAL_SOLDIER_POSITION = (0, 0)
FLAG_POSITION = ((SCREEN_COLUMNS - FLAG_WIDTH) * SQUARE_WIDTH,
                       (SCREEN_ROWS - FLAG_HEIGHT) * SQUARE_HEIGHT)

STEP = 1

UP = 'UP'
DOWN = 'DOWN'
LEFT = 'LEFT'
RIGHT = 'RIGHT'