SQUARE_WIDTH = 22
SQUARE_HEIGHT = 22
SCREEN_ROWS = 25
SCREEN_COLUMNS = 50
SCREEN_WIDTH = SQUARE_WIDTH * SCREEN_COLUMNS
SCREEN_HEIGHT = SQUARE_HEIGHT * SCREEN_ROWS
GREEN = (55, 125, 61)
BACKGROUND_COLOR = GREEN
BLACK = (14, 15, 14)
BACKGROUND_NIGHT_COLOR = BLACK
INITIAL_TEXT = """Welcome to The Flag game.  
Have Fun!"""
FLAG_WIDTH = 4 ###
FLAG_HEIGHT = 4 ###
SOLDIER_WIDTH = 2 ###
SOLDIER_HEIGHT = 4 ###
